### PR TITLE
Add removeprefix and removesuffix to pystring

### PR DESCRIPTION
**Pull request by niclasr**
Add removeprefix and removesuffix to pystring.
Python 3.9 added [removeprefix and removesuffix](https://docs.python.org/3/library/stdtypes.html#str.removeprefix)
methods to Pythons string class. Add them to
pystring to match the interfaces.

### CODE REVIEW

**Comment by grdanny** [comment]
Hello There,

Thanks for the pull request, this is a good suggestion!
Since this is a Sony Imageworks open source project we would need you to fill in and sign our  CLA which you can find here:
http://opensource.imageworks.com/cla/

Feel free to let me know if you have any questions.

Thanks again!

**Comment by niclasr** [comment]
I have signed the CLA and sent it to iamgeworks office in Culver City, I hope it has arrived.

**Comment by lgritz** [comment]
@niclasr I'm not sure anybody has ever sent a CLA to us in the post before, and I'm also not sure who's going to receive it after 2 years of everybody working from home.

Please just email an image of the signature page to opensource@imageworks.com

**Comment by niclasr** [comment]
Ok I will do that.

**Pull request merged**
