### PR TITLE
Implement the wrapper for direct return vector<string> for issue #12

### PR DESCRIPTION
**Pull request by clhsieh**
A wrapper that can direct return vector<string> for split and partition

### CODE REVIEW

**Comment by brenthuisman** [comment]
I would like to thank the original authors and @clhsieh for his pull request. It works beautifully as a drop-in replacement for similar function I puzzled together.

**Review by lgritz — APPROVED** [review]
In a >= C++11 world, this is a nice improvement.

**Comment by andry81** [comment]
> In a >= C++11 world, this is a nice improvement.

Is that enough to automatically enable a move semantic? I've though that is not enough, the author must use `std::move` + `&&` pointer including all particular overloadings for all cases to fully enable C++11 "world".

**Comment by lgritz** [comment]
@andry81 Yes! In C++11, the when you return an object from a function, move is implied. Furthermore, the modern compilers also will use named return value optimization (NRVO) so generally if optimization is turned on, it will construct right into the caller's variable where it's assigned, so not even incur the cost of a move.

https://en.cppreference.com/w/cpp/language/copy_elision

(For passing rvalues *into* a function, you do need rvalue refs, and must use std::move if you have to turn an lvalue ref into an rvalue ref.)

**Comment by andry81** [comment]
> Furthermore, the modern compilers also will use named return value optimization (NRVO) so generally if optimization is turned on, it will construct right into the caller's variable where it's assigned, so not even incur the cost of a move.

That was working long before the C++11.

**Pull request merged**
